### ISSUE TITLE
"An Error has occurred" at wiki revision history page

### ISSUE THREAD

**Issue by mauk81** [grails-samples/grails-website#65]
click on the clock icon at [wiki page](https://grails.org/wiki/WikiSyntax) -> [500 Internal Server Error](https://grails.org/wiki/info/WikiSyntax)

**Comment by lhotari** [comment]
Thanks for reporting this. Seems to be caused by the ehcache version change from 2.4.8 -> 2.9.0 . grails-website is now running on Grails 2.5.0 .

There is a mailing list discussion about the ehcache version change problems:
https://groups.google.com/d/msg/grails-dev-discuss/57bpHvzHH3I/Td4p12d2WBkJ

**Comment by lhotari** [comment]
https://github.com/grails-samples/grails-website/commit/6cb7b9340575edc87df074d83b3a7c65fc1bcf04 is a workaround for the problem

**Comment by lhotari** [comment]
Fixed. grails.org is now using the most recent revision.
